### ISSUE TITLE
Generated configs fail to marshal

### ISSUE THREAD

**Issue by KyleTryon** [TechSquidTV/uhs-cli#14]
While the generated configuration files are accurate and built from our go structs, once written to YAML it appears we are unable to then unmarshal it back into the structs. This functionality is necessary for being able to edit individual section of config without rewriting the entire file.

I am a bit new to Go so I am not yet aware of the issue and will do more research on this soon, I needed to write it down first so I do not forget.

**Comment by shrtkv** [comment]
A raf of the structure/functionalities would be cool to work on it. Trying to be more active in OSC, so if you need a UX  specialist contributing with it, ping me. 

(I mean, I gonna try to watch here, yet kinda new with the web-ui/gh realm of the open source community)

**Comment by KyleTryon** [comment]
@shrtkv That sounds great, I was actually planning on re-doing the UX of the CLI. If you'd be interested in taking a crack at it, that would be great. I am actually going to open a new issue for the topic now to kick off the discussions with the current ideas I had.

Created #17
